name: Test File Changes
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count changed files in multiple folders
        id: count-changes
        run: bash ./scripts/count_changes.sh ${{ github.sha }} code/html temp-images
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Print changed file counts
        run: |
          echo "Number of changed files in code folder: ${{ steps.count-changes.outputs.code_html_count }}, images folder: ${{ steps.count-changes.outputs.temp_images_count }}"

      - name: Run code if there are changes in code folder
        if: ${{ steps.count-changes.outputs.code_html_count > 0 }}
        run: |
          echo "Running additional steps because there are changes in html/code folders."
          # Add your custom commands here

      - name: Run code if there are changes in images folder
        if: ${{ steps.count-changes.outputs.temp_images_count > 0 }}
        run: |
          echo "Running additional steps because there are changes in temp images folders."
          # Add your custom commands here
