name: Test File Changes
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count changed files in multiple folders
        id: count-changes
        run: bash ./scripts/count_changes.sh code images
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Print changed file counts
        run: |
          echo "Output from script:"
          cat $GITHUB_OUTPUT

      - name: Run code if there are changes in code folder
        if: ${{ steps.count-changes.outputs.code_count > 0  }}
        run: |
          echo "Running additional steps because there are changes in code folders."
          # Add your custom commands here


      - name: Run code if there are changes in images folder
        if: ${{ steps.count-changes.outputs.images_count > 0 }}
        run: |
          echo "Running additional steps because there are changes in image folders."
          # Add your custom commands here
      
